- id: primary-horizon
  type: group
  role: [primary-horizon]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: [hiera, fuel_pkgs, globals, tools, logging,
    netconfig, hosts, firewall, horizon-firewall, ssl-keys-saving,
    ssl-add-trust-chain, deploy_start, primary-cluster,
    horizon-vip, primary-cluster-haproxy, openstack-haproxy-stats,
    memcached, apache, horizon-hiera-override, horizon-haproxy,
    openstack-haproxy-horizon, horizon-detached, muranodashboard-detached]
  parameters:
    strategy:
      type: one_by_one

- id: horizon
  type: group
  role: [horizon]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: [hiera, fuel_pkgs, globals, tools, logging,
    netconfig, hosts, firewall, horizon-firewall, ssl-keys-saving,
    ssl-add-trust-chain, deploy_start, cluster, horizon-vip, cluster-haproxy,
    openstack-haproxy-stats, memcached, apache, horizon-hiera-override, horizon-haproxy, 
    openstack-haproxy-horizon, horizon-detached, muranodashboard-detached]
  parameters:
    strategy:
      type: parallel

- id: horizon-hiera-override
  version: 2.0.0
  type: puppet
  role: '*'
  requires: [globals]
  required_for: [logging, horizon]
  parameters:
    puppet_manifest: 'hiera-override.pp'
    puppet_modules: '/etc/puppet/modules'
    timeout: 120

- id: horizon-haproxy
  type: puppet
  role: [primary-horizon,horizon]
  version: 2.0.0
  required_for: [horizon,deploy_end]
  requires: [deploy_start, horizon-vip, primary-cluster-haproxy,
    cluster-haproxy,horizon-detached]
  parameters:
    puppet_manifest: 'horizon-haproxy.pp'
    puppet_modules: '/etc/puppet/modules'
    timeout: 3600

- id: horizon-vip
  type: puppet
  version: 2.0.0
  role: [primary-horizon,horizon]
  required_for: [deploy_end]
  requires: [primary-cluster, cluster]
  cross-depends:
    - name: /(primary-)?cluster$/
      role: self
  parameters:
    puppet_manifest: '/etc/puppet/modules/osnailyfacter/modular/virtual_ips/virtual_ips.pp'
    puppet_modules: '/etc/puppet/modules'
    timeout: 3600

- id: horizon-firewall
  type: puppet
  version: 2.0.0
  role: [primary-horizon, horizon]
  requires: [globals,firewall]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: 'horizon-firewall.pp'
    puppet_modules: /etc/puppet/modules
    timeout: 180

- id: horizon-detached
  type: puppet
  version: 2.0.0
  role: [horizon, primary-horizon]
  required_for: [deploy_end]
  requires: [apache,horizon-vip]
  parameters:
    puppet_manifest: 'detached-horizon.pp'
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: muranodashboard-detached
  type: puppet
  version: 2.0.0
  role: [horizon, primary-horizon]
  required_for: [deploy_end]
  requires: [horizon-detached]
  parameters:
    puppet_manifest: "muranodashboard.pp"
    puppet_modules: "/etc/puppet/modules"
    timeout: 3600

- id: horizon-settings
  type: puppet
  role: '*'
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  parameters:
    puppet_manifest: "horizon-settings.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1200

- id: upgrade_horizon_packages
  type: puppet
  role: '*'
  required_for: [post_deployment_end]
  requires: [post_deployment_start, horizon-settings]
  parameters:
    puppet_manifest: "upgrade_horizon_packages.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1200

- id: lbaas-dashboard
  type: puppet
  role: '*'
  required_for: [post_deployment_end, upgrade_horizon_packages]
  requires: [post_deployment_start]
  parameters:
    puppet_manifest: lbaas_dashboard.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 720

#- id: maniladashboard-detached
#  type: puppet
#  role: '*'
#  required_for: [post_deployment_end]
#  requires: [post_deployment_start]
#  parameters:
#    puppet_manifest: "maniladashboard.pp"
#    puppet_modules: puppet/modules:/etc/puppet/modules
#    timeout: 1200
